services:
    app.s3_client:
        class: Aws\S3\S3Client
        arguments:
            -
                version: 'latest'
                region: 'eu-central-1'
                credentials:
                    key: '%env(AMAZON_S3_ACCESS)%'
                    secret: '%env(AMAZON_S3_ACCESS_SECRET)%'